artifactory:
  image: mattgruter/artifactory
  ports:
   - "8080:8080"
   - "80:80"
  volumes:
    - /home/gianluca/Projects/artifactory-repositories/data:/artifactory/data
    - /home/gianluca/Projects/artifactory-repositories/logs:/artifactory/logs
    - /home/gianluca/Projects/artifactory-repositories/backup:/artifactory/backup
  